project:
  type: book

book:
  title: "PHC 7054 Advanced Biostatistics III"
  author: "Gabriel J. Odom, PhD, ThD"
  date: "February 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/bernoulli_20250310.qmd
    - chapters/binomial_20250310.qmd
    - chapters/negative_binomial_20250310.qmd
    - chapters/poisson_20250310.qmd
    - chapters/exponential_20250310.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



