project:
  type: book

book:
  title: "A Primer on Statistical Distributions"
  subtitle: "PHC 7054 Advanced Biostatistics III"
  author: "Gabriel J. Odom, PhD, ThD"
  date: "February 2025"
  chapters:
    - index.qmd
    # - intro.qmd
    - chapters/bernoulli_20250310.qmd
    - chapters/binomial_20250310.qmd
    - chapters/negative_binomial_20250310.qmd
    - chapters/poisson_20250310.qmd
    - chapters/exponential_20250310.qmd
    - chapters/theory_gamma_function_20250707.qmd
    - chapters/gamma_20250310.qmd
    - chapters/beta_20250310.qmd
    - chapters/normal_20250310.qmd
    - chapters/chi_square_20250310.qmd
    - chapters/students_t_20250310.qmd
    - chapters/f_20250310.qmd
    - references.qmd
    - LICENSE.md

bibliography: references.bib

format:
  html:
    theme: cosmo



